version: "3.0"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      apinetwork:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    networks:
      apinetwork:
networks:
  apinetwork:
    driver: bridge
